### ISSUE TITLE
MVP to advertise

### ISSUE THREAD

**Issue by eric79** [virtual-world-framework/vwf#125]
- [x] Fix demo server once for all ( Issue #176 )
- [x] Fix issue with website freezing in Firefox on Macs
- [ ] Fix Windows installer so it does not overwrite user's PATH variable and repost it to website (Issue #155)
- [x] Investigate 503 errors when downloading the Mac build
- Documentation
  - Revamp documentation to make sure people don't get lost
    - [x] Demo page: Add link to browser requirements up top and update link to browser requirements in error text)
    - [x] Tutorial: Move pong app to the top of it
    - [ ] Rewrite Tutorial section to make it more obvious to developer to download `.dae` files (see Issue #310 )
    - [ ] Reorganize
    - [ ] Go through the whole site looking for broken links
    - [ ] Add a bit about the four things necessary to maintain synchronization
      - Stuff that you want to synchronize must be stored on the model side in a node property
      - There must not be any stateful variables in your model components that are not properties
      - Do not use calledMethod or firedEvent in the view except for things that are ephemeral (happen and then are gone) – nothing stateful
      - New for event handler replication: Do not have any local variables or functions in your model components – closures will not be preserved
    - [ ] Add a "pitfall" about having properties that are arrays or Objects w/ nodes in them
    - [ ] Add a “pitfall” that warns of putting private functions in behaviors
    - [ ] Test in all sorts of browsers with all sorts of widths
    - [ ] Can csr generation be completed in one step like this? `openssl req -new -newkey rsa:2048 -nodes -sha256 -out server.csr -keyout server.key`
  - [ ] Remove examples that we no longer want
  - [ ] Fix up remaining examples: refactor and comment so they make for good examples
  - [ ] Add a recipe for each one, including one for adding sound and video with jPlayer driver (clean up jPlayer driver in the process)
- Respond to website feedback that we've already gotten
  - [x] Change title tagline on page to better tell VWF story
  - [ ] Eliminate load timeout errors on demo server
  - [ ] Respond to Metaverse's comments via email and on the forum
  - [ ] Do a better job of explaining: What is VWF?
  - [ ] Put something in the default app that is created, so people know it's working
  - [ ] Change background of duck app to white
  - [ ] Adjust lighting to make it more beautiful (try to find three.js plugin for three light setup – or standard lighting setup in 3DS Max)
  - [ ] Make left-click and drag spin the duck
- [ ] Add a news blog to VWF site, where we can post about upcoming features, releases, and breaking changes
- [ ] Point people at Stack Overflow and gitHub issues (maybe in footer) - and enact process by which we check these regularly
- [ ] Make browser incompatibility message be more specific (again) about what failed
- Remove section about _initializeCamera_ from _Getting Started_
  - [x]  Complete PR #95: fix example/multiuser (second user's screen is black - first bad commit 543d52) - Step through code to see which part of new code it's getting tripped up in (probably has something to do w/ taking control of the navObject)
  - [ ] Edit _Getting Started_ to reflect the change
- [ ] Decrease load time on public server
  - Start loading apps before `document.ready`
  - Move to node server
  - Profile to see the biggest issue (mars-game would be a good example)
  - Decrease download time
    - Investigate glTF as an alternative to collada
    - Compress 3D model files for transport
      - Minify
      - Gzip?
- Improve demo page experience (change layout to something more like kineticjs or chrome experiements)
  - [ ] Patch kimray valve with XPC animation fixes so we can patch the version on demo server
  - [ ] Add text that explains what user can do
  - [ ] Fix “join current session” functionality
  - [ ] Fix Mars Game multiuser experience
  - Fix and post LCS app
    - [ ] Once VCTE is posted, remove command-center from VWF repo
    - [ ] Do interactive rebase on latest three.js version and drop our commit that changed “uv” to “uvMap”
    - [ ] Release VWF to Master
    - [ ] Copy LCS app to demo server
  - [ ] Add XPC
  - [ ] Fix and add Cesium-webrtc [3192](http://redmine.virtualworldframework.com/issues/3192) and [3107](http://redmine.virtualworldframework.com/issues/3107)
  - Make bzflag really shine
    - [ ] Make it not die at 15 people
      - Rendering? (what happens when you have 15 tanks?)
      - Network traffic? (reduce key and mouse events – remove mouse events that aren’t necessary)
    - [ ] Componentize navigation so users can create their own that still reduces latency - have bzflag use that kind of navigation
    - [ ] Focus on game mechanics (take out bzflag stuff and just have tanks shoot each other) - maybe update outdated code at the same time
    - [ ] Add shaders / improved art to make it look amazing
  - [ ] Add something 2D
  - [ ] Have demo.virtual.wf serve up (once again) the unsupported.html in IE 8 - (right now, the loading screen just sits forever)
  - [ ] Have app tell Eric's phone that it won’t run on it
  - [ ] Add link to VWF video (especially for unsupported browsers)
- [ ] Have downloads page be a matrix of current and past installers
- [ ] Show webpage to people and get feedback
- [x] Remove flash from VWF website to avoid sending the wrong signal (and since it doesn't work on mobile devices)
- [ ] Process pull requests
- [ ] Process Issues and other things we've heard from users like:
  - Experience of loading a new scenario and knowing when everything has been loaded could be better (start with an `onSceneReady` function)
  - _Loading_ spinner doesn't always make sense
  - In _Multiuser_ cookbook, mention the `makeOwnAvatarVisible` flag
- [ ] Reach out to all the people who have posted pull requests or issues and see what their experience has been
- [ ] Plan a conference experience
- [ ] Advertise!
- [ ] Stress test the system and document how well it can scale and document
- [ ] Update wikipedia page to be a little more human-readable - decide what we want to say and say it
- [x] Launch the website (see [to-do list](https://github.com/virtual-world-framework/vwf-web/issues/3))
- [x] Improve graphical performance (complete branch/view-interpolation)
- [x] Fix bugs and move integration to master and give us these wonderful features: websocket network check, no scroll bars, view interpolation, Current Sessions, no need for initializeCamera
  - Fix view interpolation bug (PR #149)
  - Humvee and radio lessons don't load - Issue [3189](http://redmine.virtualworldframework.com/issues/3189) and [3190](http://redmine.virtualworldframework.com/issues/3190)
  - Duck does not load [3193](http://redmine.virtualworldframework.com/issues/3193)
  - Put up warning about occasional load timeouts on command-center - Issue [3188](http://redmine.virtualworldframework.com/issues/3188)
  - Merge readme [pull request](https://github.com/virtual-world-framework/vwf/pull/140)
  - Investigate slowness of apps in Firefox
- [x] Add a comment in the default app created by `vwf create` that points the user to the _Getting Started_ guide (PR #137)
- [x] Remove unnecessary libraries from framework (bootstrap, etc) and update demos so they still work (include necessary libraries in the apps, themselves) (PR #133)
- [x] Add Google Analytics back to download page somehow
