### ISSUE TITLE
VWF 1.0

### ISSUE THREAD

**Issue by eric79** [virtual-world-framework/vwf#127]
- Advertise
  - [ ] Complete _MVP to Advertise_ to-do list (Issue #125)
  - [ ] Have people contact us if they want to put a demo up on our site
  - [ ] Add a blog to website w/ announcements/news
  - [ ] Add vwf twitter account that we monitor
- Documentation 1.0
  - [ ] Redesign documentation with user experience/flow in mind, including
    - `gotProperty`
    - `calledMethod`
    - how to know when the application has loaded: `initializedNode`
    - dynamic mesh creation
  - [ ] Improve example apps so that they actually follow current best practices
  - [ ] Create and post _Getting Started_ screencast
  - [ ] Complete API documentation
  - [ ] Show browser support grid (for core for each driver)
  - [ ] Point people at Stack Overflow to ask questions (have someone on team subscribed to vwf tag to watch for questions)
  - [ ] Open invitation for _office hours_ call
  - [ ] Remove forum
- Core 1.0: State synchronization should just work
  - [ ] Replicate dynamically-added scripts (listeners & behaviors) (PR #141, #142, #143, #144, #145, #146)
  - [ ] Design ideal persistence solution and implement it
  - [ ] Merge model sandboxing branch
  - [ ] Replicate deletions from a component
- Node.js server
  - Fix node server bugs
    - [x] Going to a named app (editor.vwf) still loads index.vwf on node server
    - [ ] Node server possibly reads yaml files wrong that end w/ a “:”?
    - [ ] Set up node to run in production mode
    - [ ] What else?
  - [ ] Switch to node.js server in production
  - [ ] Rewrite installation docs to focus around the node.js server
  - [ ] Refactor nodeJS Serving Modules (Redmine #2890)
  - [ ] Update File Caching in NodeJS to deal with YAML and JSON files and parsing (Redmine #2887)
  - [ ] Add a 404 page that doesn't have the vestiges of the old website
  - [ ] Can we make `vwf` and `vwf create` work well for those who pulled VWF down from github, too? (right now it needs the path to node.js to be added to the path, and it gives no errors when it fails)
- Deployment
  - [ ] Document deployment on at least one PaaS service (Heroku, Nodejitsu, etc) - Figure out if our embedded software conflicts with the PaaS
  - [ ] Document deployment on AWS / own hardware - Pick a modern linux flavor, go to town
  - [ ] Design deployment technique to deploy only minimal client/server (no examples, no website) - See meteor's `meteor bundle`
- Threejs 1.0 
  - [ ] Modularize view driver to allow: users to insert pieces into the render loop or override it completely ( for shaders, multiple viewports, etc), navigation, view interpolation, etc
- Payload size
  - [ ] Reduce it as much as we can and then brag about it on website (look into shrinking or removing Google Closure, among other things)
