### ISSUE TITLE
Improve the new user experience

### ISSUE THREAD

**Issue by jessmartin** [virtual-world-framework/vwf#68]
Right now, it's hard to get started using VWF. We should make that experience awesome. To that end, I wrote an [Ideal README](https://github.com/virtual-world-framework/vwf/blob/development/README-1.0.md). That gave rise to the set of issues captured below.

**Website**
- [x] As a product owner, I want an example app with source code embedded into website home page [#2956](http://redmine.virtualworldframework.com/issues/2956)

**Documentation**
- [x] As a developer, I want a clearer README [#2954](http://redmine.virtualworldframework.com/issues/2954)
- [x] As a developer, I want a one-page documentation site [#2923](http://redmine.virtualworldframework.com/issues/2923)

**Install**
- [x] As a developer, I want one bash script to install VWF on Mac or Linux [#2957](http://redmine.virtualworldframework.com/issues/2957)
- [x] As a developer, I want to install without building anything (pre-built binaries) [#2958](http://redmine.virtualworldframework.com/issues/2958)
- [x] As a Windows developer, I want a bootstrap exe that will download and install everything [#2959](http://redmine.virtualworldframework.com/issues/2959)
- [x] As a product owner, I want the bash script to be available at http://get.virtual.wf [#2960](http://redmine.virtualworldframework.com/issues/2960)
- [ ] As a product owner, I want to track downloads on the bash install script [#2961](http://redmine.virtualworldframework.com/issues/2961)

**Quick Start**
- [x] As a developer, I want a command-line interface for creating VWF apps [#2962](http://redmine.virtualworldframework.com/issues/2962)
- [x] As a developer, I want to run vwf inside of a folder with only my app [#2962](http://redmine.virtualworldframework.com/issues/2962)
- [x] As a developer, I want a command-line interface for starting the VWF server for my app [#2963](http://redmine.virtualworldframework.com/issues/2963)

**Badges**
- [x] As a product owner, I want to display the build status in the README [#2964](http://redmine.virtualworldframework.com/issues/2964)

**Examples**
- [ ] As a product owner, I want a screencast of building an awesome app quickly with VWF [#2965](http://redmine.virtualworldframework.com/issues/2965)

**Community**
- [ ] As a product owner, I want to provide an IRC channel to potential users [#2966](http://redmine.virtualworldframework.com/issues/2966)
- [ ] As a product owner, I want to respond to questions about VWF on Stack Overflow [#2967](http://redmine.virtualworldframework.com/issues/2967)
